# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "ggateway:cx6222580@tcp(139.198.181.33:13306)/ggateway?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100